### ISSUE TITLE
Final report

### ISSUE THREAD

**Issue by kkira07** [Teaching-projects/SZE-MOSZE-2020-VoicePlay#22]

**Comment by hegyhati** [comment]
Matenak 4, tobbieknek 5.

**Comment by hegyhati** [comment]
@VMatthew kerlek ird meg gyorsan a neptun kodod elso betujet, mert ketten is vagytok ezzel a nevvel :-(

**Comment by vbence121** [comment]
Nem a Máté 😅 de ha minden igaz G7BMO6 a neptun kódja.

**Comment by hegyhati** [comment]
@vbence121 koszi, beirtam a kis tablazatomba, kommentet toroltem, perelheto lennel erte :-D
